name: Verbinal
options:
  bundleIdPrefix: com.codebg
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.codebg.Verbinal
    MARKETING_VERSION: "1.0.4"
    CURRENT_PROJECT_VERSION: "5"
    PRODUCT_NAME: Verbinal
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: A4ABW5VD88
targets:
  Verbinal:
    type: application
    platform: macOS
    sources:
      - Verbinal
    settings:
      base:
        INFOPLIST_FILE: Verbinal/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.codebg.Verbinal
        CODE_SIGN_ENTITLEMENTS: Verbinal/Verbinal.entitlements
  VerbinalTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - VerbinalTests
    dependencies:
      - target: Verbinal
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.codebg.VerbinalTests
        PRODUCT_NAME: VerbinalTests
        PRODUCT_MODULE_NAME: VerbinalTests
